services:
  db:
    image: postgres:15-alpine
    container_name: pparty-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pparty
    ports:
      - "5432:5432"
    volumes:
      - pparty_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/pparty"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CI=true
    depends_on:
      - backend

volumes:
  pparty_data: